# Generated by Django 4.2.19 on 2025-03-22 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(db_index=True, default=datetime.datetime(2025, 3, 22, 15, 35, 32, 809229), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 22, 15, 35, 32, 809229), verbose_name='Опубликована'),
        ),
    ]
