# Generated by Django 4.2.19 on 2025-03-22 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_blog_content_alter_blog_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(db_index=True, default=datetime.datetime(2025, 3, 22, 16, 7, 32, 104101), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 22, 16, 7, 32, 104101), verbose_name='Опубликована'),
        ),
    ]
