# Generated by Django 4.2.19 on 2025-04-20 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_comment_image_blog_image_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 4, 20, 21, 28, 14, 287098), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2025, 4, 20, 21, 28, 14, 288098), verbose_name='Дата комментария'),
        ),
    ]
